### ISSUE TITLE
missing yearbooks

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#10]
a few of the yearbooks aren't showing up on the landing pages. for example, here's the 1971 yearbook: https://digitalcollections.barnard.edu/object/yearbook-1971/mortarboard-1971#page/1/mode/2up.

it doesn't show up on the default landing page (http://digitalcollections.barnard.edu/yearbook?page=3&display=grid&islandora_solr_search_navigation=0) or when you limit to the results to the 1970s: (https://digitalcollections.barnard.edu/yearbook?display=grid&islandora_solr_search_navigation=0&f[0]=mods_originInfo_dateCreated_sort%3A%5B1968-01-01T00%3A00%3A01Z%20TO%201978-01-01T00%3A00%3A01Z%5D)

The pages show up in a general browse (https://digitalcollections.barnard.edu/islandora/search?type=dismax&islandora_solr_search_navigation=0&date_format=Y&f[0]=mods_originInfo_dateCreated_sort%3A%5B1971-01-01T00%3A00%3A00Z%20TO%201971-12-31T00%3A00%3A00Z%5D)

The date metadata looks the same as yearbooks that are showing up--is it possible that some yearbooks were missed in re-indexing? 

This is happening for a number of yearbooks--I can try to figure out how many/which ones if that's helpful.

**Comment by br2490** [comment]
This is a Solr hiccup :-1:  The reindex is going as fast as possible on the production server.

I'll think of a work around in the meanwhile.

**Comment by MarthaTenney** [comment]
ah ok! as long as it is something that will be resolved fairly soon, I don't think we need a workaround.

**Comment by br2490** [comment]
Resolved.
