### ISSUE TITLE
A (very) few missing items from BCRW ingest

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#12]
By my count (from the spreadsheet), there should be 552 items in the BCRW collection, but I only see 546. Is there an easy way to see if any errors were thrown or to run a check on the filenames in the collection?

**Comment by br2490** [comment]
@MarthaTenney I've performed a query to get you a list of all objects ingest. There are indeed only 546 and here they are: https://gist.github.com/br2490/803f25f5e8928b76344860e5c584a62d

**Comment by br2490** [comment]
According to the diff these are missing:

Letter from Catharine Stimpson to Allan Farnsworth, December 28, 1971
Letter from Jeannette Mirsky to Martha Peterson, October 30, 1971
Letter from Martha Peterson to Catharine Stimpson, December 14, 1971
Notes from Executive Committee meeting, November 18, 1971
Questionnaire: Women Faculty of Columbia University, 1970
Reports for Executive Committee meeting, October 26, 1971

**Comment by br2490** [comment]
Ingested missing material.  Tagging @MarthaTenney and marking as resolved.

**Comment by MarthaTenney** [comment]
thank you!
