### ISSUE TITLE
breadcrumbs not working as expected on photographs

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#14]
https://digitalcollections.barnard.edu/object/1156/student-reading-wollman-library-stacks-circa-1970s

breadcrumbs are showing default behavior (using record group/collection) rather than genre (which would be photographs and direct back to the photographs landing page)

**Comment by br2490** [comment]
Resolved by @MarthaTenney, closing.
