### ISSUE TITLE
links to newspaper pages not working from search page (dev update issue)

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#17]
try clicking on one of the newspaper pages from this search page: http://160.39.115.62/islandora/search/peterson?type=dismax

**Comment by br2490** [comment]
Notes: this was previously fixed in our theme.inc

**Comment by br2490** [comment]
This was fixed a while ago, failed to note it here.

I just tested and it appears working.  @MarthaTenney if you want to verify and close, I'd be gracious.

**Comment by MarthaTenney** [comment]
looks good to me! thank you, closing.
