### ISSUE TITLE
search call issue on manuscript page search results (possible dev update issue)

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#18]
from this search, try clicking on one of the manuscript pages: http://160.39.115.62/islandora/search/peterson?type=dismax

errors attached

![searchcall2](https://cloud.githubusercontent.com/assets/7797222/19400589/d8441e9e-9224-11e6-9a81-f4f087396add.png)
![searchcall](https://cloud.githubusercontent.com/assets/7797222/19400590/d8446fb6-9224-11e6-95e2-f15048e90835.png)

**Comment by br2490** [comment]
Notes: this was previously patched in our theme.inc. Review what changes occurred and revise.

**Comment by br2490** [comment]
IAB doesn't like to cooperate on dev.  This still appears to be an issue on dev.  Will need to revisit.

**Comment by MarthaTenney** [comment]
this seems to be working now! closing out.
