### ISSUE TITLE
highlighting/secondary search broken on book page results (possible dev update issue)

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#19]
from this search, try clicking on one of the pages of the literary magazine: http://160.39.115.62/islandora/search/Lightman%20?type=dismax

![booksearchissue](https://cloud.githubusercontent.com/assets/7797222/19400677/42e09c32-9225-11e6-9d63-4ff882947208.png)

this issue seems familiar--not sure if iti is new since the update. will do additional tests.

**Comment by br2490** [comment]
Notes: this was previously fixed in our theme.inc. Check to see if why it's not working on dev, and as Martha notes, was it ever working? (I think so.)

**Comment by br2490** [comment]
This appears functioning normally on production.  I think our development box, the MD, or Solr core not keeping up - especially for this item in particular.

**Comment by MarthaTenney** [comment]
ok!
