### ISSUE TITLE
book metadata and permalink not appearing on item view

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#20]
see this object for example: https://160.39.115.62/object/why-we-strike-1970/why-we-strike-1970#page/1/mode/2up

set in config to have the same metadata display as a photograph (which does seem to be working, see https://160.39.115.62/islandora/object/islandora%3A87)

![bookmetadatapermalink](https://cloud.githubusercontent.com/assets/7797222/19401132/8e4592a2-9227-11e6-869d-6fe39dbcd42e.png)

**Comment by br2490** [comment]
jQuery version bump. Resolves #20.
