### ISSUE TITLE
Broken breadcrumb on Manuscript pages

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#22]
Per MT, 10/25/2016:

[We're] losing the breadcrumb for the item when you're on [a manuscript] page:

https://digitalcollections.barnard.edu/object/25/regulations-affirmative-action-contract-compliance-programs-end-sex-based-discrimination

should look like this but with page appended:
https://digitalcollections.barnard.edu/object/20/regulations-affirmative-action-contract-compliance-programs-end-sex-based-discrimination

**Comment by MarthaTenney** [comment]
looks good to me! sorry for not entering this on github in the first place.

**Comment by br2490** [comment]
Resolved by 75dc883
