### ISSUE TITLE
Slow indexing--update HOCR doc types

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#23]
We ran into the same issue with slow indexing and I think we've determined the issue; your HOCR datatstreams have a doc type and Java tries to validate them.

See https://github.com/Islandora/islandora_ocr/blob/7.x/includes/hocr.inc#L571-L582 for the root of the issue. eg: https://digitalcollections.barnard.edu/islandora/object/bc:bulletin-19960925-12/datastream/HOCR/view

The updates to Drupal and Islandora on your prod are now complete. We did run into an issue with a random error being displayed with the Drupal update but it turned out to cache related and corrected itself after a bit of head banging.

The cached error and debugging the slow indexing put us over what we originally thought it would take to finish off the update but the good news is we've narrowed down the issue! The next step is to go and clean up all your HOCR datastreams. You basically need to query all page objects that have a HOCR DS, run this command https://github.com/Islandora/islandora_ocr/blob/7.x/includes/hocr.inc#L584, and save the DS back to the object. Did you want us to take care of this for you?

**Comment by br2490** [comment]
Resolved by https://github.com/BarnardArchives/barnard_islandora/commit/c77b8e4c6a903834fc46e731ce9ee8b8d85f1e8b
