### ISSUE TITLE
New breadcrumb behavior for BCRW collection

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#25]
all items with this relatedItem tag:

<relatedItem type="host">
<titleInfo>
<title>Barnard Center for Research on Women</title>
</titleInfo>
<identifier type="local">BC13-58</identifier>
<typeOfResource>mixed material</typeOfResource>
</relatedItem>

should have breadcrumbs that direct back to the BCRW landing page (https://digitalcollections.barnard.edu/bcrw). so the breadcrumbs for the item should look like:

Home > Collections > BCRW (link to landing page) > Item

or, for the page:
Home > Collections > BCRW > Item > Page 

Use the acronym, BCRW, for the breadcrumb. (I thought about including in the breadcrumbs a link back to a canned solr search for the record group that these items are in, Academic Departments and Programs, but at this point decided against it since all we have from that record group are BCRW items and it would just make the breadcrumbs longer and less intuitive). 

We'll also add a button to the collections page closer to the launch date (tba)

**Comment by br2490** [comment]
@MarthaTenney breadcrumb behavior for review on Islandoradev as time permits.

**Comment by MarthaTenney** [comment]
working beautifully for me! thank you, Ben
