### ISSUE TITLE
Single Page View 

### ISSUE THREAD

**Issue by cristinafontanez** [BarnardArchives/digitalcollections.barnard.edu#26]
Need to set up default single page for: 

From diary19031908: 042 
From diary Class Diary: 024

**Comment by br2490** [comment]
objects can now be set to one-up at will.
this was specific to the BC15 ingest, Scrapbooks: in that context this task is complete.  All scrapbooks, diaries, etc. in BC15 will have IAB in pushed to mode 1.

Think this has been tested, but yes, will still need testing and verification. 

tagging @cristinafontanez @MarthaTenney

**Comment by MarthaTenney** [comment]
Yeah, since everything is defaulting to 1-up view, I think this is resolved. @cristinafontanez would you confirm?
