### ISSUE TITLE
BCRW button

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#27]
It's been a while since I've made a collection button, so I forget what elements you need. The image for the BCRW collection button is here: N:\Archives\Web Content\Files for Digital Collections\New buttons\Final buttons\bcrw.jpg

And the text should be: 
BCRW
Documents from the founding of the Barnard Center for Research on Women

[the above text may change, getting final approval from BCRW staff]. 

Would it be possible to mock up the button on dev and then put it on prod at some point on Monday 3/13, in advance of the collection launch? 

Thank you!

**Comment by br2490** [comment]
tagging: @MarthaTenney 👍 

Ready for review http://islandoradev/collections

Text overflows: depending on your discussions with BCRW we can shrink the description txt if it should remain that long.

**Comment by MarthaTenney** [comment]
beautiful! maybe switch it to just "Documents from the Barnard Center for Research on Women" for now--we're going to be adding non-founding docs in the future anyway. thank you!

**Comment by br2490** [comment]
Resolved with https://github.com/BarnardArchives/barnard_islandora/commit/45428f40a9192533383a736f6b3e6f2f5f173940 and HTML updates.
