### ISSUE TITLE
Date slider missing; error on search

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#28]
Date slider is missing and an error about a missing file on search results--see attached.
![dateerror](https://cloud.githubusercontent.com/assets/7797222/23957985/20250d94-0977-11e7-8dcc-a7515f2e6379.png)

Steps to repeat:
https://digitalcollections.barnard.edu/islandora/search/%22eileen%20power%22?type=dismax&islandora_solr_search_navigation=0&f[0]=mods_originInfo_dateCreated_sort%3A%5B1928-01-01T00%3A00%3A01Z%20TO%201978-01-01T00%3A00%3A01Z%5D

**Comment by br2490** [comment]
Updated module, failed to reset perms on a directory. Resolved without commits.
