### ISSUE TITLE
Scrapbook/diary search results functionality

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#29]
Clicking on a a page of a compound object (scrapbook/diary) should bring you to the whole compound object, to that page (with a highlighted term if a keyword was entered) within the IA bookviewer. Currently it brings you to the page object.

Search results:
https://digitalcollections.barnard.edu/islandora/search?type=dismax&islandora_solr_search_navigation=0&f%5B0%5D=mods_genre_ms%3A%22diaries%22

Page object: 
https://digitalcollections.barnard.edu/object/214/stella-bloch-hanau-diary-vol-1-1903-1908-page-2

This functionality is in place for book object search results: 
https://digitalcollections.barnard.edu/islandora/search?type=dismax&islandora_solr_search_navigation=0&f%5B0%5D=mods_genre_ms%3A%22yearbook%22

- [x] Review theme commits: #7dac4e5, #c1ef4c9, #76d7eeb 
- [x] Review what was in place prior to those commits
- [x] Review updated modules that now seem to include these commits in their core.

- [x] Solr alters for pages, books, compounds.
- [x] Searching and highlights on forced views and scrapbooks.
  - [ ] ? http://digitalcollections.barnard.edu/object/1219/jessie-may-wendover-scrapbook-1892-1896-page-123/pages
  - [ ] check js/css - what is going on in the compound view 👎

**Comment by br2490** [comment]
@MarthaTenney updated series of SOLR alters - found many redundancies and removed them.  this update will require testing on both development and production.  

**Code updated.  Needs review.**

**Comment by MarthaTenney** [comment]
I looked at this on dev  and it appears to be working: 

sample search page - https://160.39.115.62/islandora/search?type=dismax&islandora_solr_search_navigation=0&f%5B0%5D=mods_relatedItem_host_titleInfo_title_ms%3A%22Alum%5C%20Scrapbooks%22

clicking on a result brings you to the correct page or inclusion within the viewer, e.g. the third result brings you here: https://160.39.115.62/object/19/grace-r-greenbaum-epstein-scrapbook-1911-1913#page/2/mode/1up

but now this functionality doesn't work for yearbooks (at least on dev); see this search and try clicking a result: https://160.39.115.62/islandora/search?type=dismax&islandora_solr_search_navigation=0&f%5B0%5D=mods_genre_ms%3A%22yearbook%22

@cristinafontanez would you verify? 
@br2490 have you implemented the fix for scrapbooks on production? if so I don't think it's working there.

**Comment by br2490** [comment]
i'll push this change to production and test it in a few (it is a significant update). I will revert if necessary, else woot.

**Comment by br2490** [comment]
tagging @BarnardArchives/core 

search has been fixed per @MarthaTenney.

**Comment by br2490** [comment]
[ ] - Review theme commits: [7dac4e5](https://github.com/BarnardArchives/barnard_theme/commit/4d173134d522979ddc50c1cd088303cae7dac4e5), c1ef4c9, 76d7eeb 
[ ] - Review what was in place prior to those commits
[ ] - Review updated modules that now seem to include these commits in their core.
[ ] - Searching and highlights on forced ~ or just in general?

**Comment by br2490** [comment]
@MarthaTenney we have search functionality, I think. Please try some searching!

**Comment by MarthaTenney** [comment]
Yay this is looking so much better! As far as I can tell this is working as it should be.
