### ISSUE TITLE
GIT structure cleanup

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#32]
After our last vendor update by DGI we're left in a GIT-SUBMODULE limbo state.  

Determine if we're going to use GIT or DRUSH to keep digitalcollection up-to-date; discuss with team/current vendor.

Read up on why one of the other - and determine if instinct to return to a git submodule structure is a worthy time investment?  

Possibly kick this to CM after recent shift in hours?  

tagging @MarthaTenney

**Comment by MarthaTenney** [comment]
I would be cool with kicking this up to Common Media for their advice... shall I open a ticket?

**Comment by br2490** [comment]
@MarthaTenney thank you!  I've created a ticket for CM in an attempt to outline all of my confusion about what to do next.  @MarthaTenney do you have a preference if we use drush (much more accessible) versus git submodule?

**Comment by MarthaTenney** [comment]
either way is fine by me--I have only recently started learning how to use drush but would be happy to learn about git submodule stuff too.

**Comment by br2490** [comment]
superseded by #50.
