### ISSUE TITLE
deprecate current social media icons in favor of nothing

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#34]
Task complete on development.  

Review required.

tagging @MarthaTenney

**Comment by MarthaTenney** [comment]
Looks good to moi! Okay by me to push to production.

**Comment by br2490** [comment]
removed since commit https://github.com/BarnardArchives/barnard_theme/blob/f772b659fd98c4598c5157d91b3f59cbe51e2159/template.php#L164-L167
Closing!
