### ISSUE TITLE
Solr HOCR Alter for COMPOUND OBJECTS

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#36]
Currently when viewing an object that is a compound object search does not work.  

assumption: presumably because it's checking the <compound object> for the HOCR and such a DS shouldn't exist on that...  Will need to verify and if this is the case this might be a js or a hook result alter.... i think for the former. 

tagging: @MarthaTenney 
(we need to find and add CF to this repo, and I imagine CM/BD!)

**Comment by MarthaTenney** [comment]
Is this about highlighting on search results? Or something else? Sorry having a brain block.

**Comment by br2490** [comment]
yes!  i think the ticket is poorly worded on my part.

this ticket s/is/was about HOCR on objects we ingest with OCR DS, so occurs no highlighting on those pages.

I'm in favor of changing this from bug to enhancement and queueing it.

**Comment by MarthaTenney** [comment]
right, there's no way to have hocr for things that we transcribe by hand. I think we can remove this issue altogether--we've explored ways to do this in the past and haven't come up with anything. would love to talk about training tesseract on handwriting and difficult typescript though....
