### ISSUE TITLE
arrghh breadcrumbs!

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#39]
A weird thing is happening on our [/about](https://digitalcollections.barnard.edu/about) page: there appears to be a breadcrumb leading back to the Home page. Same for /collections and /exhibits. Is this possibly a result of recent code changes? (I think this is desirable/fine for pages in exhibits, e.g. [this one](https://digitalcollections.barnard.edu/exhibits/student-publishing-barnard#page5), but otherwise don't want it on non-Islandora-object pages).

**Comment by br2490** [comment]
@MarthaTenney an update to resolve this breadcrumb has been pushed as a fix to both servers. I do not see additional errors at present.

**Comment by MarthaTenney** [comment]
looks good to me! thank you ben!
