### ISSUE TITLE
Thumbnail caption

### ISSUE THREAD

**Issue by cristinafontanez** [BarnardArchives/digitalcollections.barnard.edu#41]
Can we move the caption for the inclusion thumbnails so that they appear below the thumbnail instead of above? @br2490

**Comment by br2490** [comment]
@cristinafontanez - this style change has been made on development for your review. Can send screenshots if remote, just let me know.

tagging @BarnardArchives/owners

**Comment by cristinafontanez** [comment]
Thanks
