### ISSUE TITLE
Resize Inclusions header 

### ISSUE THREAD

**Issue by cristinafontanez** [BarnardArchives/digitalcollections.barnard.edu#42]
@br2490 can you resize 'Inclusions' header so that it's bigger than the inclusions' captions?

**Comment by br2490** [comment]
@cristinafontanez - this style change has been made on development for your review. Can send screenshots if remote, just let me know.

tagging @BarnardArchives/owners

**Comment by cristinafontanez** [comment]
I saw it. Looks good, thanks!
