### ISSUE TITLE
error with date encoding

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#43]
Check MODs in BC15.x for date encoding issues in all relevant DSIDs and normalize or set appropriately.

**Comment by MarthaTenney** [comment]
I noticed this too on the diary https://digitalcollections.barnard.edu/islandora/object/BC15-12%3A172/datastream/MODS/view

**Comment by MarthaTenney** [comment]
@cristinafontanez and I will look for other date encoding issues!

**Comment by br2490** [comment]
- [ ] Fix existing collections where the date is M/D/Y to YYYY-MM-DD.
- [ ] Review where the ingest script is processing dates and fix.
- [ ] See exported CSV from Google Drive is a possible cause.  doubtful, but possible change in frmt.

**Comment by MarthaTenney** [comment]
Oh, just checked and it was an issue of Excel converting the date format in the original CSV. Damn you Excel! I've fixed the CSV in N:\Archives\Digital Materials\BC15.0x-ACTIVE-INGEST-FOLDER-notouch\03-batch-10-5-2017-a and it should work now. Sorry for the oversight.

**Comment by MarthaTenney** [comment]
@br2490 to install I/O module, I will work on updating dates!
