### ISSUE TITLE
15.02 woes

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#44]
current approach (https://digitalcollections.barnard.edu/object/0/jessie-may-wendover-scrapbook) is not working.

@cristinafontanez to re-organize 15.02 into separate directories for each page. @br2490 will ingest each page directory as its own book object, pages of the book object made up of all the images in the directory, default to thumbs view.

**Comment by br2490** [comment]
- [ ] Purge existing collection.
- [ ] Ingest on all clear.
_one book per page, combining all sources from that page_

**Comment by br2490** [comment]
If the current ingest of BC15.02 is okay - disregarding the odd page issue - I think my understanding is this is safe to close?  @cristinafontanez feel free to confirm and if you agree, please close this issue!
