### ISSUE TITLE
Title spacing bug

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#45]
Issue with spacing in titles (causing mis-ordering) of Eleanor Myers Jewett collection: https://digitalcollections.barnard.edu/object/0/eleanor-myers-jewett-scrapbook-collection. Ben to investigate, possibly use find and replace? Or this module? https://github.com/ulsdevteam/islandora_datastreams_io

**Comment by br2490** [comment]
YES YES YES to CRUD and DS_IO.  Toodles F&R!

**Comment by br2490** [comment]
reopening.  The label for all need to be updated.  👍

**Comment by br2490** [comment]
fcr labels updated per status in #46 👍 
closing!
