### ISSUE TITLE
something funky with isMemberOf status on scrapbooks

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#46]
just looked at the "collection" pages for the scrapbook collections and found that a number of them show not only the scrapbook objects but also inclusion objects. so the hierarchical relationship that should exist (collection > scrapbook item > page > inclusion) is messed up. 

on the overview page it looks correct (1 member): https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A0/manage

but if you go to the collection page you see all the inclusion objects:
https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A0/manage/collection#share-children

the rels-ext for one of [those inclusions](https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A737/manage/datastreams) is: 

<rdf:RDF xmlns:fedora="info:fedora/fedora-system:def/relations-external#" xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:islandora="http://islandora.ca/ontology/relsext#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/BC15-20:737">
    <fedora-model:hasModel rdf:resource="info:fedora/islandora:bookCModel"></fedora-model:hasModel>
    <fedora:isMemberOf rdf:resource="info:fedora/BC15-20:0"></fedora:isMemberOf>
    <islandora:hasLanguage rdf:resource="info:fedora/eng"></islandora:hasLanguage>
    <fedora:isConstituentOf rdf:resource="info:fedora/BC15-20:1004"></fedora:isConstituentOf>
    <islandora:isSequenceNumberOfBC15-20_1004>214</islandora:isSequenceNumberOfBC15-20_1004>
  </rdf:Description>
</rdf:RDF>

which shows a isConstituentOf relationship (to the [scrapbook object](https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A1004/manage)) as well as a isMemberOf relationship to the scrapbook collection.

Maybe it needs to be structured like this in order to display correctly?

I'm also seeing two objects on the [top level](https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A0/manage/collection#share-children) - a [book object](https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A1/manage) and a [compound object](https://digitalcollections.barnard.edu/islandora/object/BC15-20%3A1004/manage). 

Ack, so sorry for not noticing this earlier!

@br2490 let me know if you want to have a phone call to discuss.

**Comment by br2490** [comment]
@MarthaTenney let's have a call.  I've pulled a sample of RELS-EXT DS from BC15.20 here: https://gist.github.com/br2490/4a3acd2638d2ba5438c84cbc2a6112d6

**Comment by MarthaTenney** [comment]
as noted in chat, this also appears to be an issue with multi-object collections, e.g https://digitalcollections.barnard.edu/islandora/object/BC15-14%3A0/manage/collection

**Comment by br2490** [comment]
Confirming this issue in detail:  the script is assuming the relationship between inclusions is to the collection, not to the book it was included in.  For future ingests either check on changing the RELS behavior for compound inclusion objects (matches === 5) OR see:

**Comment by br2490** [comment]
Ben check isMemberOfCollection - you missed those on all TLO belonging to main the Alumna's collection and used isMemberOf. Collection Policy states isMemberOfCollection is the correct predicate for membership.

**Comment by br2490** [comment]
check all ingested collections from rg BC15.x
- [ ] BC15-02
- [ ] BC15-04
- [ ] BC15-05
- [ ] BC15-06
- [ ] BC15-07
- [ ] BC15-08
- [ ] BC15-09
- [ ] BC15-12
- [ ] BC15-14
- [ ] BC15-18

**Comment by br2490** [comment]
RELS_EXT_isMemberOfCollection_uri_t:"BC15"
AND
(RELS_EXT_hasModel_uri_s:"info:fedora/islandora:bookCModel"
OR
RELS_EXT_hasModel_uri_s:"info:fedora/islandora:compoundCModel")

@cristinafontanez @MarthaTenney this is complete and resolves title spacing, date conversion error, and relationships.  Please advise 😄
