### ISSUE TITLE
Add modules CRUD and Datastream IO

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#49]
Per #45 install:
https://github.com/mjordan/islandora_datastream_crud
https://github.com/ulsdevteam/islandora_datastreams_io

Will be helpful in #47, #45 (init), and #43 

tagging @MarthaTenney @cristinafontanez

**Comment by br2490** [comment]
Confirmed working on dev and pushed to production.

**Comment by br2490** [comment]
@MarthaTenney: this resolves #45 and #43.

**Comment by MarthaTenney** [comment]
holy moly this is so cool
