### ISSUE TITLE
Jessie May Wendover scrapbook (BC15-02) search issues

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#52]
I think the issues with the Wendover scrapbook (the one that we are ingesting as a book of books) are just too much -- noted recently that it is producing a ton of irrelevant results on a search of the collection (see https://digitalcollections.barnard.edu/scrapbooks?cq=catch_all_fields_mt%3A%28girl%29&display=grid&islandora_solr_search_navigation=0) plus the issue with the search calls inside the item, the multi-page display, issues it causes with OAI-PMH harvesting, etc.... I am leaning toward just removing this item and ingesting it as a diary object (just a series of tons of pages with all the inclusions in sequence). What do you think @br2490 ?

_per our conversation_

- [x] temporarily hide ... or maybe just remove entirely existing BC15-02 namespace
- [x] reingest collection as a book   XXXXXX: be mindful of sequencing from pageNumber_inclusionID_inclusionPageNumber.
- [x] ping Martha for review once this is complete (and edit the rest of this)
- [x] check export for 7S
- [x] delete: [books of inclusions OR diary book]

**Comment by br2490** [comment]
updated main comment with tasks after conversation.

**Comment by br2490** [comment]
Updating other relevant tickets, but please let me know how this looks in terms of OAIMHP.

**Comment by MarthaTenney** [comment]
OAI PMH issues look to be resolved!

**Comment by br2490** [comment]
Protocol for metadata harvest - got it!  Not metadata harvest protocol.  Glad it's looking better 👍

**Comment by br2490** [comment]
@MarthaTenney all searching for this should actually be working.  I had not coded the variable_get for the 1up/thumb enforcing on the theme side of the Drupal factory.
