### ISSUE TITLE
MD Check for frances-hope-purdon-leavitt-scrapbook

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#54]
I think there may be an error in MD for author and/or dates.  

Authors name in search results includes date...
http://digitalcollections.barnard.edu/object/0/frances-hope-purdon-leavitt-scrapbook

**Comment by MarthaTenney** [comment]
Ah! Thank you for noticing. I think that is an error from the original metadata spreadsheet. Should we do a find and replace or datastreams IO?

<namePart>Purdon Leavitt, Frances Hope, 1884-1951</namePart>

should be replaced with 

<namePart>Purdon Leavitt, Frances Hope</namePart>

**Comment by br2490** [comment]
Metadata update is complete.  My review, both MODS and DC are updated and accurate for create.  

For your review and closing/next steps @MarthaTenney.

**Comment by MarthaTenney** [comment]
Thank you!
