### ISSUE TITLE
transcripts missing for some pages of stella bloch hanau vol. 3

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#55]
for example: http://digitalcollections.barnard.edu/object/347/stella-bloch-hanau-diary-vol-3-1907-1911#page/101/mode/2up

I went to check if we ever had transcript files for these pages, but I need to reorganize the files from the ingest directory--is it okay to move them back (or copy them back) into their correct directories?

**Comment by br2490** [comment]
I'm sorry I didn't see your question in here until now.  
Yes please copy/move/edit/delete and I will digress to how you want to proceed.  If it was just a shift or something similarly simple it could likely be automated on / in islandora!

**Comment by br2490** [comment]
Folders reorganized. Reviewing Stella

**Comment by br2490** [comment]
@MarthaTenney OCR datastreams pushed.  Closing this ticket.   There may be no need to rename the files if that folder will eventually be deleted.
