### ISSUE TITLE
missing metadata on scholar and feminist objects

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#57]
because of hard-coded subjects https://github.com/BarnardArchives/barnard_islandora_drush/blob/master/includes/bc_islandora.drush_mods_data.inc#L522-L534

scholar and feminist items ingested are missing boilerplate subjects, see
https://docs.google.com/spreadsheets/d/1QQ_KzW0q_Zd06nlhlG-5djdbNCGY3JbXK8z1R1ePvaU/edit#gid=195535030

use datastreams io to inject the subjects back in

**Comment by br2490** [comment]
@MarthaTenney 
Objects updated, ingesting the remainder of the collection that failed.

resolved by [22beda0](https://github.com/BarnardArchives/barnard_islandora_drush/commit/22beda0c26e23eb543e4b5016ed183395ddf79cf)

Still need to escape ampersands in abstracts - add this to script to escape.

**Comment by br2490** [comment]
resolved by 22beda0
