### ISSUE TITLE
Alum Mag ingest

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#60]
BC11-08 is almost ready for ingest! Metadata [here](https://docs.google.com/spreadsheets/d/14jCsCR6yUQ4bEwf82xp2ci4hJbh22sJ-wVfv06orHak/edit#gid=1324054287), files on server in Archives>Temp>AlumMags. 

I still need to resolve rights metadata, but sample MODS/test ingest would be appreciated as a first step!

**Comment by br2490** [comment]
todo
- [ ] Parent Collection location && PID (BC11-08:0, top level collection || nested in collection BC11 (however that RG exists presently in Fedora))
- [ ] Breadcrumbs once the above
- [ ] There should always be a third.

**Comment by br2490** [comment]
isle-development server results:  https://belle.benjaminrosner.com/object/0/alumnae-magazine
fsg->Solr did not work, likely because of me! :}

**Comment by MarthaTenney** [comment]
to work out: suppressing certain fields, like rights statements, from keyword searches (but not from solr entirely).
