### ISSUE TITLE
Add Barnard Magazine and scrapbook buttons to /collections page

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#63]
Hi all! Finally getting around to adding buttons for the scrapbooks and alum magazine collections.

Images are here: https://github.com/BarnardArchives/barnard_islandora/tree/master/img
New buttons are barnardmagazine.jpg and scrapbooks.jpg. 

These should be added to the /collections landing page with the following links/text:

- [x] Barnard Magazine:
  - link: http://digitalcollections.barnard.edu/barnard-magazine
  - title text: Barnard Magazine
  - subheading: The magazine of Barnard's alums, from 1912-2014

- [x] Scrapbooks:
  - link: http://digitalcollections.barnard.edu/scrapbooks
  - title text: Scrapbooks
  - subheading: Turn-of-the-century scrapbooks and diaries of Barnard students and alums

Let me know if you have any questions!

**Comment by br2490** [comment]
@MarthaTenney this is ready for review on Islandoradev/collections

**Comment by br2490** [comment]
Hi @MarthaTenney, we have updated the Islandoradev/collections page with some updates including CSS/images/etc. The new section of images has replaced the old on dev. Please let me know!

**Comment by br2490** [comment]
Resolved by https://github.com/BarnardArchives/digitalcollections.barnard.edu/pull/68
