### ISSUE TITLE
Bug on details of BCRW materials

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#69]
This is not urgent and can definitely wait until your return! I just noticed that the details block (descriptive metadata) is not expanding on BCRW materials, e.g. http://digitalcollections.barnard.edu/object/1987/scholar-and-feminist-conference-ix-program-1982

**Comment by br2490** [comment]
Commit 401d7a1 resolves #69, but will open #70, the manuscript transcripts no longer update because the hook that was used, onPageChange() was removed.
