### ISSUE TITLE
existing transcript upload

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#7]
ingest script: look for txt file with same name (transcript) -> use as OCR datastream. Dillon may already have written this into the script but I have not verified and it definitely hasn't been tested. test documents in N:\Archives\Digital Materials\TEMPORARY\Manuscript Solution Pack Test\Handwritten with existing transcript

**Comment by br2490** [comment]
Prelim testing reveals more investigation required.

**Comment by br2490** [comment]
To do:

https://github.com/BarnardArchives/barnard_islandora_drush/blob/master/includes/bc_islandora.drush_ingest_methods.inc#L241
update function create_page_object
- check for text/plain file with corresponding object
- pass path of OCR file to create_page_object(...)

https://github.com/BarnardArchives/barnard_islandora_drush/blob/master/includes/bc_islandora.drush_ingest_helpers.inc#L151
update function create_page_object 
- add param for OCR stream (path to file).
- if (OCR) create OCR DS and ingest into object.

**Comment by br2490** [comment]
I think I ignored everything I put in here as a comment. Good going Ben! Partially resolved with https://github.com/BarnardArchives/barnard_islandora_drush/commit/b709fd31837d90703d019f5f54b9161db60340c2

**Comment by br2490** [comment]
Tagging @MarthaTenney and closing issue #5 and #7.
