### ISSUE TITLE
Solr view collection page landing queries are not functional

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#73]
The Solr collections view pages don't seem to be functional--it seems like the the more narrow "landing page" queries are not being run, just the broader "search queries". Here is an example page: http://digitalcollections.barnard.edu/node/72/edit

As you can see, the landing page is defaulting to the broader query (mods_relatedItem_host_titleInfo_title_s:"Alum Scrapbooks"--which [looks like this](https://digitalcollections.barnard.edu/islandora/search?islandora_solr_search_navigation=0&f%5B0%5D=mods_relatedItem_host_titleInfo_title_s:%22Alum%20Scrapbooks%22) when you run it), not the more narrow landing page query (RELS_EXT_isMemberOf_uri_ms:"info:fedora/BC15:0" - which [looks like this](https://digitalcollections.barnard.edu/islandora/search?islandora_solr_search_navigation=0&f%5B0%5D=RELS_EXT_isMemberOf_uri_ms:%22info:fedora/BC15:0%22))

This is the case for all the landing pages that I've seen. Ben, could you take a look at this? Thank you!

**Comment by br2490** [comment]
@MarthaTenney really interesting bug because I'm not sure what changed. The logic in the module has since been updated and it is working on development. I will push these changes to the appropriate repo in a moment, tag this issue, and merge to production. 

We may want to circle back to this as a wildcard search (or an empty search) will reveal the pages because the module identifies that as a "user search"
@MarthaTenney how would you feel about changing this behavior so an "empty" search still uses the collection query rather than the less specific search query?

**Comment by MarthaTenney** [comment]
Looking beautiful, thank you @br2490 !!

I'd be great with changing the behavior so an "empty" search still uses the collection query. But it's not super high priority--let me know if it would be a lot of work for you!

**Comment by br2490** [comment]
Primary issue resolved. @TODO implement last comment from @MarthaTenney in re: empty q using default query.

**Comment by MarthaTenney** [comment]
Just realized this and thought this functionality might have existed in previous versions of the code, but it would be great for *only* a date search to be treated as an empty search and keep to the landing page results (rather than full search/page results). Example is [here](http://digitalcollections.barnard.edu/yearbook?display=grid&islandora_solr_search_navigation=0&date_format=Y&f%5B0%5D=mods_originInfo_dateCreated_sort%3A%5B1990-01-01T00%3A00%3A00Z%20TO%202000-12-31T00%3A00%3A00Z%5D); it would be great to still only see the mortarboard issues, not the pages, when the only query is a date query.

**Comment by br2490** [comment]
@MarthaTenney I will see about getting to this after #79

**Comment by MarthaTenney** [comment]
Hi Ben! I'm bumping this question to see if you could adjust a date search to be treated as an empty search--that is, show landing page results (i.e. issues) for searches where the only parameters are dates.
