### ISSUE TITLE
Update solr search count text for new theme

### ISSUE THREAD

**Issue by br2490** [BarnardArchives/digitalcollections.barnard.edu#75]
On search result page:
Remove  "({page number} of {max page number} {count of results})" (AKA islandora-solr-result-count)
Make heading "{count of results} Search results"

Did we want to hide islandora-solr-result-count on ALL pages it appears?
Did we want to include {count of results} on ALL pages it _could_ appear?

@MarthaTenney @elanaalt

**Comment by MarthaTenney** [comment]
Hi Ben! Thinking of a few possible additional places where this might be relevant:

Do we want to include {count of results} (and hide islandora-solr-result-count) on a blank search http://160.39.115.62/islandora/search/?type=dismax ? My inclination is yes. 

And on collections pages too, e.g. http://160.39.115.62/collections/photographs?display=grid&islandora_solr_search_navigation=0&f%5B0%5D=mods_subject_topic_ms%3A%22College%5C%20campuses%22. Yes from me here too.

If there are other scenarios that you're imagining, let me know.

**Comment by elanaalt** [comment]
sounds good to me!

**Comment by br2490** [comment]
@MarthaTenney @elanaalt this has been implemented - please review and let me know if it should appear in other spots as well.

**Comment by MarthaTenney** [comment]
Looks good, except could the text everywhere read "Search results"? I am noticing that it incorporates collection language on the collections pages, which makes sense when it says "5 Photographs" but less sense when it says "7 Mortarboard": http://160.39.115.62/yearbook?display=grid&islandora_solr_search_navigation=0&f%5B0%5D=mods_subject_topic_ms%3A%22Women%27s%5C%20colleges%22 Thank you, Ben!

**Comment by br2490** [comment]
Closing issue for now.
