### ISSUE TITLE
Resolve discrepancies in RELS EXT on BCRW collection

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#76]
Previously added items items in the collection use "    <fedora:isMemberOf rdf:resource="info:fedora/BCRW:BarnardCenterForResearchOnWomen"></fedora:isMemberOf>"

and the newly-added audio recordings use     <fedora:isMemberOfCollection rdf:resource="info:fedora/BCRW:BarnardCenterForResearchOnWomen"></fedora:isMemberOfCollection>

see our previous convos on this https://github.com/BarnardArchives/digitalcollections.barnard.edu/issues/46

**Comment by br2490** [comment]
@MarthaTenney Is the collection ready for this update or should I pause? Once I push this it should update the collection page to include newly ingest items.
Plan: update RELS to match. I also think a reindex wouldn't be out of the question.

**Comment by MarthaTenney** [comment]
Sorry for the delay, it has been a day! Would pushing it re-ingest items or just update existing items' RELS? I just realized that we have been doing some work creating compound objects for multi-tape recordings, and I don't want to mess that up

**Comment by br2490** [comment]
No worries ever! Just update. If we had to reingest I would have cried!

Best,
Ben

IA Developer and Support Specialist
IMATS, Barnard Library and Academic Information Services

(212) 854-9005

**Comment by br2490** [comment]
Predicate and value resolved. 
-isMemberOfCollection
+isMemberOf
value: BCRW:BarnardCenterForResearchOnWomen
