### ISSUE TITLE
Illegal choice on solution pack config

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#77]
When I try to select and save a configuration on the Compound Solution pack config page, I get an error message about an illegal choice. Ben, could you look at this or let me know if I should ask Born Digital to investigate?

![illegalchoice](https://user-images.githubusercontent.com/7797222/65542560-6a0ebc00-dedd-11e9-9d4a-fa5f2ac7c518.png)

**Comment by br2490** [comment]
@MarthaTenney I think this was resolved.  Just needed to select a query provider, I think?  Plz review and update or close!
Thank you!

**Comment by MarthaTenney** [comment]
Yes! working great, thank you!
