### ISSUE TITLE
Adding corrected transcripts to Scholar & Feminist tapes

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#79]
Transcripts that have been corrected (but not yet converted to WebVTT format) are in an 'edited' directory within the transcripts directory on the n drive. I just realized this means that they weren't ingested with the rest of the transcripts (so the most accurate transcripts are not on the digital collections hehe). I looked at adding them through the Islandora UI, but the "uncorrected" transcript is not an accepted datastream for the oral history solution pack there. 

I have a couple of asks:

- Would you be able to add the plain text transcripts for these tapes (as uncorrected transcript datastreams)?
- If we are able to correct more transcripts, what should the workflow be for replacing the uncorrected transcript datastream with a plain text corrected file (even if it stays as an "uncorrected" transcript datastream)? I think we can just add the WebVTT files through the interface.

**Comment by br2490** [comment]
@MarthaTenney I have created the ability to upload updated uncorrected transcripts to objects with that datastream existing. 
For other objects that did not have an uncorrected transcript, one can be added even if it is not within the solution pack's composite. Adding a new "UNCORRECTED_TRANSCRIPT" datastream will suffice on objects without one. 
I can go through an manually add these, but I have no way of doing it automatically.

**Comment by MarthaTenney** [comment]
Thanks, Ben! Kaya is working on adding plain-text transcripts and all seems to be working fine. We talked about it and think that having the default action to download the WebVTT transcript (when it is available) is fine--timestamps might be helpful for some people to have in the downloaded file, and they don't seem obtrusive even if they're not needed. 

Is the solr indexing the uncorrected/plain text or the webvtt transcripts?

**Comment by MarthaTenney** [comment]
I have one other request for this, @br2490: Would it be possible to update the text for the download link slightly? For items where the download is of the uncorrected transcript datastream (.txt file) I'd like it to say "Download: Uncorrected Transcript (contains errors)". For items that have the trancript (.vtt file) available to download, I'd like it to say "Download: Timestamped Transcript (VTT file; view using text editor)"

**Comment by br2490** [comment]
@MarthaTenney This is available for review @ http://160.39.115.62/object/189/scholar-and-feminist-xi-women-and-resistance-literature-traditional-and-new-forms-womens.  Note the VTT _is not_ for that OBJ. 

Did you want the ability to download _both_ the VTT and uncorrected_transcript if they exist? I thought not and have coded it as such. I don't think it would make much sense, but want to present that option. BOTH will show on DEV so you can review how the links will present. This will NOT be the case on production unless you indicate so.

Also, did you want to consider adding the ability to download the MP3? I added that and can quickly remove it.

**Comment by MarthaTenney** [comment]
Thank you Ben, this is perfect! Yes, only showing VTT if it exists or the uncorrected_transcript if it doesn't is good. And the mp3 download is great too! Thank you, if you can push this to production I think we're set.
