### ISSUE TITLE
Landing page search behavior

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#8]
Change search behavior so that expanded search is only triggered when a keyword search is performed (on its own or with facets). The goal of this is to not see newspaper and yearbook pages unless a keyword search has been performed

**Comment by br2490** [comment]
@MarthaTenney pushed patch to production (low stakes patch). Please review!

**Comment by MarthaTenney** [comment]
looks great to me! checking on it made me realize there's something funky happening with the yearbooks, so I'll open a new bug for that.
