### ISSUE TITLE
Copy in landing page search boxes

### ISSUE THREAD

**Issue by MarthaTenney** [BarnardArchives/digitalcollections.barnard.edu#9]
A little additional copy in the advanced search box--either help text or at top of box: "Search within this collection." Not sure if we need one for the facets--what do you think?

**Comment by br2490** [comment]
@MarthaTenney How does this read as a first pass attempt? https://gist.github.com/br2490/56f9eb7a2aeb26df66fb4cec3fdb493b#file-copy-attempt-1-png

**Comment by br2490** [comment]
@MarthaTenney bump

**Comment by MarthaTenney** [comment]
Sorry, I had commented on the image but not here: how about just "SEARCH THIS COLLECTION"? and "Sort by:"

**Comment by br2490** [comment]
@MarthaTenney update pushed to: https://islandoradev/collections/mortarboard

**Comment by MarthaTenney** [comment]
Perf! Slightly unrelated but is there a way to indicate that the default (date created ascending) is selected?

**Comment by br2490** [comment]
Yup! Should be all there now.
